# NetUP Universal Dual DVB-CI FPGA firmware
# http://www.netup.tv
#
# Copyright (c) 2014 NetUP Inc, AVB Labs
# License: GPLv3

# TCL File Generated by Component Editor 11.1sp2
# Mon Apr 14 02:24:53 MSD 2014
# DO NOT MODIFY


# +-----------------------------------
# | 
# | avalon64_to_avalon8 "avalon64_to_avalon8" v1.0
# | AVB 2014.04.14.02:24:53
# | 
# | 
# | 
# |    ./avalon64_to_avalon8.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module avalon64_to_avalon8
# | 
set_module_property NAME avalon64_to_avalon8
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR AVB
set_module_property DISPLAY_NAME avalon64_to_avalon8
set_module_property TOP_LEVEL_HDL_FILE avalon64_to_avalon8.vhd
set_module_property TOP_LEVEL_HDL_MODULE avalon64_to_avalon8
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME avalon64_to_avalon8
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file avalon64_to_avalon8.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter OUT_ADDR_WIDTH INTEGER 15
set_parameter_property OUT_ADDR_WIDTH DEFAULT_VALUE 15
set_parameter_property OUT_ADDR_WIDTH DISPLAY_NAME OUT_ADDR_WIDTH
set_parameter_property OUT_ADDR_WIDTH TYPE INTEGER
set_parameter_property OUT_ADDR_WIDTH UNITS None
set_parameter_property OUT_ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property OUT_ADDR_WIDTH HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 address address Input "(out_addr_width-4) - (0) + 1"
add_interface_port avalon_slave_0 byteenable byteenable Input 8
add_interface_port avalon_slave_0 writedata writedata Input 64
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 readdata readdata Output 64
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink rst reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end out_address export Output out_addr_width
add_interface_port conduit_end out_writedata export Output 8
add_interface_port conduit_end out_write export Output 1
add_interface_port conduit_end out_readdata export Input 8
add_interface_port conduit_end out_read export Output 1
add_interface_port conduit_end out_waitrequest export Input 1
# | 
# +-----------------------------------
