# NetUP Universal Dual DVB-CI FPGA firmware
# http://www.netup.tv
#
# Copyright (c) 2014 NetUP Inc, AVB Labs
# License: GPLv3

# TCL File Generated by Component Editor 11.1sp2
# Wed Apr 16 14:58:21 MSD 2014
# DO NOT MODIFY


# +-----------------------------------
# | 
# | ci_bridge "ci_bridge" v1.0
# | AVB 2014.04.16.14:58:21
# | 
# | 
# | 
# |    ./ci_bridge.vhd syn, sim
# |    ./ci_control.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module ci_bridge
# | 
set_module_property NAME ci_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR AVB
set_module_property DISPLAY_NAME ci_bridge
set_module_property TOP_LEVEL_HDL_FILE ci_bridge.vhd
set_module_property TOP_LEVEL_HDL_MODULE ci_bridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ci_bridge
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file ci_bridge.vhd {SYNTHESIS SIMULATION}
add_file ci_control.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 byteenable byteenable Input 2
add_interface_port avalon_slave_0 writedata writedata Input 16
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 readdata readdata Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink rst reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end cia_reset export Output 1
add_interface_port conduit_end cib_reset export Output 1
add_interface_port conduit_end cia_ce_n export Output 1
add_interface_port conduit_end cib_ce_n export Output 1
add_interface_port conduit_end ci_reg_n export Output 1
add_interface_port conduit_end ci_a export Output 15
add_interface_port conduit_end ci_we_n export Output 1
add_interface_port conduit_end ci_oe_n export Output 1
add_interface_port conduit_end ci_iowr_n export Output 1
add_interface_port conduit_end ci_iord_n export Output 1
add_interface_port conduit_end cia_wait_n export Input 1
add_interface_port conduit_end cib_wait_n export Input 1
add_interface_port conduit_end cia_ireq_n export Input 1
add_interface_port conduit_end cib_ireq_n export Input 1
add_interface_port conduit_end cia_cd_n export Input 2
add_interface_port conduit_end cib_cd_n export Input 2
add_interface_port conduit_end cia_overcurrent_n export Input 1
add_interface_port conduit_end cib_overcurrent_n export Input 1
add_interface_port conduit_end cia_reset_buf_oe_n export Output 1
add_interface_port conduit_end cib_reset_buf_oe_n export Output 1
add_interface_port conduit_end cia_data_buf_oe_n export Output 1
add_interface_port conduit_end cib_data_buf_oe_n export Output 1
add_interface_port conduit_end ci_bus_dir export Output 1
add_interface_port conduit_end interrupt export Output 1
add_interface_port conduit_end cam_interrupts export Output 2
add_interface_port conduit_end cam0_ready export Output 1
add_interface_port conduit_end cam0_bypass export Output 1
add_interface_port conduit_end cam1_ready export Output 1
add_interface_port conduit_end cam1_bypass export Output 1
add_interface_port conduit_end cam0_fail export Output 1
add_interface_port conduit_end cam1_fail export Output 1
add_interface_port conduit_end ci_d_out export Output 8
add_interface_port conduit_end ci_d_in export Input 8
add_interface_port conduit_end ci_d_en export Output 1
add_interface_port conduit_end cam_writedata export Input 8
add_interface_port conduit_end cam_write export Input 1
add_interface_port conduit_end cam_readdata export Output 8
add_interface_port conduit_end cam_read export Input 1
add_interface_port conduit_end cam_address export Input 18
add_interface_port conduit_end cam_waitreq export Output 1
# | 
# +-----------------------------------
