# NetUP Universal Dual DVB-CI FPGA firmware
# http://www.netup.tv
#
# Copyright (c) 2014 NetUP Inc, AVB Labs
# License: GPLv3

# TCL File Generated by Component Editor 11.1sp2
# Sun Mar 09 09:15:53 MSK 2014
# DO NOT MODIFY


# +-----------------------------------
# | 
# | dma_arbiter "dma_arbiter" v1.0
# | AVB 2014.03.09.09:15:53
# | 
# | 
# | 
# |    ./dma_arbiter.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module dma_arbiter
# | 
set_module_property NAME dma_arbiter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR AVB
set_module_property DISPLAY_NAME dma_arbiter
set_module_property TOP_LEVEL_HDL_FILE dma_arbiter.vhd
set_module_property TOP_LEVEL_HDL_MODULE dma_arbiter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME dma_arbiter
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file dma_arbiter.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter MEM_ADDR_WIDTH NATURAL 31
set_parameter_property MEM_ADDR_WIDTH DEFAULT_VALUE 31
set_parameter_property MEM_ADDR_WIDTH DISPLAY_NAME MEM_ADDR_WIDTH
set_parameter_property MEM_ADDR_WIDTH TYPE NATURAL
set_parameter_property MEM_ADDR_WIDTH UNITS None
set_parameter_property MEM_ADDR_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property MEM_ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property MEM_ADDR_WIDTH HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink rst reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end dma0_addr export Input 61
add_interface_port conduit_end dma0_wrdata export Input 64
add_interface_port conduit_end dma0_size export Input 7
add_interface_port conduit_end dma0_write export Input 1
add_interface_port conduit_end dma0_wait export Output 1
add_interface_port conduit_end dma1_addr export Input 61
add_interface_port conduit_end dma1_size export Input 7
add_interface_port conduit_end dma1_wrdata export Input 64
add_interface_port conduit_end dma1_write export Input 1
add_interface_port conduit_end dma1_wait export Output 1
add_interface_port conduit_end dma0_byteen export Input 8
add_interface_port conduit_end dma1_byteen export Input 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_master
# | 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master readLatency 0

set_interface_property avalon_master ENABLED true

add_interface_port avalon_master mem_addr address Output mem_addr_width
add_interface_port avalon_master mem_size burstcount Output 7
add_interface_port avalon_master mem_wrdata writedata Output 64
add_interface_port avalon_master mem_write write Output 1
add_interface_port avalon_master mem_waitreq waitrequest Input 1
add_interface_port avalon_master mem_byteen byteenable Output 8
# | 
# +-----------------------------------
