# NetUP Universal Dual DVB-CI FPGA firmware
# http://www.netup.tv
#
# Copyright (c) 2014 NetUP Inc, AVB Labs
# License: GPLv3

# TCL File Generated by Component Editor 11.1sp2
# Mon Aug 18 10:27:29 MSD 2014
# DO NOT MODIFY


# +-----------------------------------
# | 
# | dvb_ts "dvb_ts" v1.0
# | AVB 2014.08.18.10:27:29
# | 
# | 
# | 
# |    ./avblabs_common_pkg.vhd syn, sim
# |    ./pid_table_ram.vhd syn, sim
# |    ./dvb_ts_filter.vhd syn, sim
# |    ./dvb_ts_sync.vhd syn, sim
# |    ./afifo_ptr.vhd syn, sim
# |    ./dvb_ts_shaper.vhd syn, sim
# |    ./dvb_ts.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module dvb_ts
# | 
set_module_property NAME dvb_ts
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR AVB
set_module_property DISPLAY_NAME dvb_ts
set_module_property TOP_LEVEL_HDL_FILE dvb_ts.vhd
set_module_property TOP_LEVEL_HDL_MODULE dvb_ts
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME dvb_ts
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file avblabs_common_pkg.vhd {SYNTHESIS SIMULATION}
add_file pid_table_ram.vhd {SYNTHESIS SIMULATION}
add_file dvb_ts_filter.vhd {SYNTHESIS SIMULATION}
add_file dvb_ts_sync.vhd {SYNTHESIS SIMULATION}
add_file afifo_ptr.vhd {SYNTHESIS SIMULATION}
add_file dvb_ts_shaper.vhd {SYNTHESIS SIMULATION}
add_file dvb_ts.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 address address Input 9
add_interface_port avalon_slave_0 byteenable byteenable Input 4
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink rst reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end interrupt export Output 1
add_interface_port conduit_end cam_bypass export Input 1
add_interface_port conduit_end dvb_in0_dsop export Input 1
add_interface_port conduit_end dvb_in0_data export Input 8
add_interface_port conduit_end dvb_in0_dval export Input 1
add_interface_port conduit_end dvb_in1_dsop export Input 1
add_interface_port conduit_end dvb_in1_data export Input 8
add_interface_port conduit_end dvb_in1_dval export Input 1
add_interface_port conduit_end dvb_in2_dsop export Input 1
add_interface_port conduit_end dvb_in2_data export Input 8
add_interface_port conduit_end dvb_in2_dval export Input 1
add_interface_port conduit_end cam_baseclk export Input 1
add_interface_port conduit_end cam_mclki export Output 1
add_interface_port conduit_end cam_mdi export Output 8
add_interface_port conduit_end cam_mival export Output 1
add_interface_port conduit_end cam_mistrt export Output 1
add_interface_port conduit_end cam_mclko export Input 1
add_interface_port conduit_end cam_mdo export Input 8
add_interface_port conduit_end cam_mostrt export Input 1
add_interface_port conduit_end cam_moval export Input 1
add_interface_port conduit_end dvb_out_dsop export Output 1
add_interface_port conduit_end dvb_out_dval export Output 1
add_interface_port conduit_end dvb_out_data export Output 8
# | 
# +-----------------------------------
