# NetUP Universal Dual DVB-CI FPGA firmware
# http://www.netup.tv
#
# Copyright (c) 2014 NetUP Inc, AVB Labs
# License: GPLv3

# TCL File Generated by Component Editor 11.1sp1
# Mon Feb 27 17:09:19 MSK 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | fifo_out_8b_sync "fifo_out_8b_sync" v1.0
# | null 2012.02.27.17:09:19
# | 
# | 
# | D:/exchange/xCode-FPGA-test/uart/fifo_out_8b_sync.vhd
# | 
# |    ./fifo_out_8b_sync.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module fifo_out_8b_sync
# | 
set_module_property NAME fifo_out_8b_sync
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME fifo_out_8b_sync
set_module_property TOP_LEVEL_HDL_FILE fifo_out_8b_sync.vhd
set_module_property TOP_LEVEL_HDL_MODULE fifo_out_8b_sync
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME fifo_out_8b_sync
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file fifo_out_8b_sync.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter FIFO_DEPTH INTEGER 16
set_parameter_property FIFO_DEPTH DEFAULT_VALUE 16
set_parameter_property FIFO_DEPTH DISPLAY_NAME FIFO_DEPTH
set_parameter_property FIFO_DEPTH TYPE INTEGER
set_parameter_property FIFO_DEPTH UNITS None
set_parameter_property FIFO_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_DEPTH AFFECTS_GENERATION false
set_parameter_property FIFO_DEPTH HDL_PARAMETER true
add_parameter BUS_WIDTH INTEGER 32
set_parameter_property BUS_WIDTH DEFAULT_VALUE 32
set_parameter_property BUS_WIDTH DISPLAY_NAME BUS_WIDTH
set_parameter_property BUS_WIDTH TYPE INTEGER
set_parameter_property BUS_WIDTH UNITS None
set_parameter_property BUS_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BUS_WIDTH AFFECTS_GENERATION false
set_parameter_property BUS_WIDTH HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 addr address Input 2
add_interface_port avalon_slave_0 in_data writedata Input 32
add_interface_port avalon_slave_0 wr_en write Input 1
add_interface_port avalon_slave_0 out_data readdata Output 32
add_interface_port avalon_slave_0 wait_req waitrequest Output 1
add_interface_port avalon_slave_0 byte_en byteenable Input 4
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink rst reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_source
# | 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset_sink
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0

set_interface_property avalon_streaming_source ENABLED true

add_interface_port avalon_streaming_source st_data data Output 8
add_interface_port avalon_streaming_source st_ready ready Input 1
add_interface_port avalon_streaming_source st_valid valid Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end irq export Output 1
# | 
# +-----------------------------------
