# NetUP Universal Dual DVB-CI FPGA firmware
# http://www.netup.tv
#
# Copyright (c) 2014 NetUP Inc, AVB Labs
# License: GPLv3

# TCL File Generated by Component Editor 11.1sp2
# Sun Apr 13 16:37:23 MSD 2014
# DO NOT MODIFY


# +-----------------------------------
# | 
# | int_ctrl "int_ctrl" v1.0
# | AVB 2014.04.13.16:37:23
# | 
# | 
# | 
# |    ./int_ctrl.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module int_ctrl
# | 
set_module_property NAME int_ctrl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR AVB
set_module_property DISPLAY_NAME int_ctrl
set_module_property TOP_LEVEL_HDL_FILE int_ctrl.vhd
set_module_property TOP_LEVEL_HDL_MODULE int_ctrl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME int_ctrl
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file int_ctrl.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink rst reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0

set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave avls_byteenable byteenable Input 4
add_interface_port avalon_slave avls_writedata writedata Input 32
add_interface_port avalon_slave avls_write write Input 1
add_interface_port avalon_slave avls_readdata readdata Output 32
add_interface_port avalon_slave avls_read read Input 1
add_interface_port avalon_slave avls_waitrequest waitrequest Output 1
add_interface_port avalon_slave avls_address address Input 13
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_cra
# | 
add_interface avalon_cra avalon end
set_interface_property avalon_cra addressAlignment DYNAMIC
set_interface_property avalon_cra addressUnits WORDS
set_interface_property avalon_cra associatedClock clock
set_interface_property avalon_cra associatedReset reset_sink
set_interface_property avalon_cra burstOnBurstBoundariesOnly false
set_interface_property avalon_cra explicitAddressSpan 0
set_interface_property avalon_cra holdTime 0
set_interface_property avalon_cra isMemoryDevice false
set_interface_property avalon_cra isNonVolatileStorage false
set_interface_property avalon_cra linewrapBursts false
set_interface_property avalon_cra maximumPendingReadTransactions 0
set_interface_property avalon_cra printableDevice false
set_interface_property avalon_cra readLatency 0
set_interface_property avalon_cra readWaitStates 0
set_interface_property avalon_cra readWaitTime 0
set_interface_property avalon_cra setupTime 0
set_interface_property avalon_cra timingUnits Cycles
set_interface_property avalon_cra writeWaitTime 0

set_interface_property avalon_cra ENABLED true

add_interface_port avalon_cra address address Input 2
add_interface_port avalon_cra byteenable byteenable Input 2
add_interface_port avalon_cra writedata writedata Input 16
add_interface_port avalon_cra write write Input 1
add_interface_port avalon_cra readdata readdata Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_master
# | 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master readLatency 0

set_interface_property avalon_master ENABLED true

add_interface_port avalon_master avlm_address address Output 15
add_interface_port avalon_master avlm_byteenable byteenable Output 4
add_interface_port avalon_master avlm_writedata writedata Output 32
add_interface_port avalon_master avlm_write write Output 1
add_interface_port avalon_master avlm_readdata readdata Input 32
add_interface_port avalon_master avlm_read read Output 1
add_interface_port avalon_master avlm_waitrequest waitrequest Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset_sink

set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender avls_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end avlm_irq export Input 16
# | 
# +-----------------------------------
